In [2]:
from vnstock import *

Index code: ''VNINDEX', 'VN30', 'HNXIndex', 'HNX30', 'UpcomIndex', 'VNXALL',
'VN100','VNALL', 'VNCOND', 'VNCONS','VNDIAMOND', 'VNENE', 'VNFIN',
'VNFINLEAD', 'VNFINSELECT', 'VNHEAL', 'VNIND', 'VNIT', 'VNMAT', 'VNMID',
'VNREAL', 'VNSI', 'VNSML', 'VNUTI', 'VNX50'

Time range : 'OneDay', 'OneWeek', 'OneMonth', 'ThreeMonth', 'SixMonths', 'YearToDate', 'OneYear', 'ThreeYears', 'FiveYears'

In [3]:
listing_companies()

,ticker,group_code,company_name,company_short_name
0,VVS,UpcomIndex,Công ty Cổ phần Đầu tư Phát triển Máy Việt Nam,Đầu tư Phát triển Máy Việt Nam
1,XDC,UpcomIndex,Công ty TNHH MTV Xây dựng Công trình Tân Cảng,Xây dựng Công trình Tân Cảng
2,HSV,UpcomIndex,Công ty Cổ phần Gang Thép Hà Nội,Gang Thép Hà Nội
3,CST,UpcomIndex,Công ty Cổ phần Than Cao Sơn - TKV,Than Cao Sơn - TKV
4,BVL,UpcomIndex,Công ty Cổ phần BV Land,BV Land
...,...,...,...,...
1625,XMP,UpcomIndex,Công ty Cổ phần Thủy điện Xuân Minh,Thủy điện Xuân Minh
1626,YBC,UpcomIndex,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,Xi măng và Khoáng sản Yên Bái
1627,YBM,VNINDEX,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,Khoáng sản CN Yên Bái
1628,YEG,VNINDEX,Công ty Cổ phần Tập đoàn Yeah1,Tập đoàn Yeah1
1629,YTC,UpcomIndex,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,XNK Y tế TP.HCM

In [4]:
ticker_overview('TCB')

,exchange,shortName,industryID,industryIDv2,industry,industryEn,establishedYear,noEmployees,noShareholders,foreignPercent,website,stockRating,deltaInWeek,deltaInMonth,deltaInYear,outstandingShare,issueShare,companyType,ticker
0,HOSE,Techcombank,289,8355,Ngân hàng,Banks,1993,9757,1901,0.225,http://www.techcombank.com.vn,4.2,0.005,-0.014,-0.192,3517.2,3517.2,NH,TCB

In [7]:
df =  stock_historical_data(symbol='GMD', 
                            start_date="2021-01-01", 
                            end_date='2022-02-25') # u can short code like erasing key code
df.head()

      Open     High      Low    Close   Volume TradingDate
0  31393.0  32344.0  31203.0  31488.0  4226500  2021-01-04
1  31488.0  32773.0  31155.0  32154.0  4851900  2021-01-05
2  32535.0  32535.0  31488.0  31774.0  3641300  2021-01-06
3  32059.0  32820.0  30917.0  32344.0  5753700  2021-01-07
4  32725.0  33106.0  31869.0  32249.0  4587500  2021-01-08

In [8]:
price_board('TCB,SSI,VND')

,Mã CP,Giá Khớp Lệnh,KLBD/TB5D,T.độ GD,KLGD ròng(CM),%KLGD ròng (CM),RSI,MACD Volume,MACD Signal,Tín hiệu KT,...,Khối lượng Dư mua,Khối lượng Dư bán,Khớp nhiều nhất,seq,vnid3d,vnid1m,vnid3m,vnid1y,vnipe,vnipb
0,TCB,26850.0,1.03,1.54,-107000,-26.2,43.902547,-0.24,Neutral,Neutral,...,127200,93000,26800,1676361540,-1.9,-1.2,9.3,-30.5,11.919,1.5671
1,SSI,18900.0,0.53,0.61,85600,15.1,45.137544,-0.24,Neutral,Neutral,...,90700,645300,18700,1676361540,-1.9,-1.2,9.3,-30.5,11.919,1.5671
2,VND,13900.0,0.62,0.83,-85000,-7.4,41.909360,-0.27,Neutral,Buy,...,453100,870400,13700,1676361540,-1.9,-1.2,9.3,-30.5,11.919,1.5671

In [11]:
df = stock_intraday_data(symbol='GMD',page_num=0,page_size=5000)
df

,price,volume,cp,rcp,a,ba,sa,hl,pcp,time
0,51700.0,17700,-300.0,0.0,,64600.0,132200.0,False,-300.0,14:45:00
1,52000.0,500,0.0,0.0,SD,64600.0,131700.0,False,-400.0,14:29:24
2,52000.0,100,0.0,0.0,SD,64600.0,131800.0,False,0.0,14:29:24
3,52000.0,200,0.0,0.0,SD,64600.0,132000.0,False,0.0,14:29:24
4,52000.0,100,0.0,0.0,SD,64600.0,132100.0,False,0.0,14:29:24
...,...,...,...,...,...,...,...,...,...,...
255,52500.0,100,500.0,0.0,BU,700.0,0.0,False,0.0,09:24:40
256,52500.0,100,500.0,0.0,BU,200.0,0.0,False,-200.0,09:22:22
257,52500.0,400,500.0,0.0,BU,600.0,0.0,False,0.0,09:22:22
258,52700.0,100,700.0,0.0,BU,100.0,0.0,False,-100.0,09:18:38
259,52800.0,700,800.0,0.0,,0.0,0.0,False,0.0,09:15:00

In [21]:
# financial ratio 
import openpyxl
"""symbol_ls: a list of ticker that needs to be compared
industry_comparison: true or false
frequency: Yearly or Quarterly"""
financial_ratio_compare (symbol_ls=['TCB', 'CTG', 'BID'], industry_comparison='True', frequency= 'Yearly', start_year=2020)

,Chỉ số,2017,2018,2019,2020,2021,2022
0,P/E,NaN,NaN,NaN,NaN,NaN,NaN
1,BID,1.931659e+01,1.579755e+01,2.156374e+01,2.392118e+01,2.021483e+01,1.206704e+01
2,TCB,1.589460e+01,1.099041e+01,7.712361e+00,1.110489e+01,9.790559e+00,4.686654e+00
3,CTG,1.578063e+01,1.476715e+01,1.015345e+01,1.031625e+01,1.096377e+01,8.157355e+00
4,BID,1.931659e+01,1.579755e+01,2.156374e+01,2.392118e+01,2.021483e+01,1.206704e+01
...,...,...,...,...,...,...,...
171,Toàn ngành,2.272894e+10,2.932384e+10,3.172492e+10,3.927128e+10,5.101939e+10,5.789796e+10
172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Dữ liệu được cung cấp bởi FiinTrade,NaN,NaN,NaN,NaN,NaN,NaN
175,https://fiintrade.vn/,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
financial_ratio("TCB", 'quarterly', True)

,ticker,quarter,year,priceToEarning,priceToBook,valueBeforeEbitda,dividend,roe,roa,daysReceivable,...,loanOnAsset,loanOnDeposit,depositOnEarnAsset,badDebtOnAsset,liquidityOnLiability,payableOnEquity,cancelDebt,ebitdaOnStockChange,bookValuePerShareChange,creditGrowth
0,TCB,4,2020,9.0,1.5,None,None,0.181,0.030,None,...,0.631,1.000,0.680,0.003,0.372,4.9,0.013,None,0.057,0.202
1,TCB,3,2020,7.0,1.1,None,None,0.177,0.030,None,...,0.575,0.913,0.682,0.003,0.440,4.7,0.015,None,0.047,0.124
2,TCB,2,2020,6.3,1.0,None,None,0.176,0.029,None,...,0.585,0.927,0.689,0.005,0.418,4.9,0.010,None,0.044,0.249
3,TCB,1,2020,5.0,0.8,None,None,0.177,0.029,None,...,0.592,0.987,0.650,0.006,0.416,5.1,0.006,None,0.039,0.416
4,TCB,4,2019,8.2,1.3,None,None,0.178,0.029,None,...,0.602,0.998,0.651,0.008,0.411,5.2,0.002,None,0.053,0.443
5,TCB,3,2019,8.8,1.4,None,None,0.172,0.027,None,...,0.559,0.939,0.639,0.010,0.469,5.2,0.003,None,0.046,0.230
6,TCB,2,2019,8.1,1.3,None,None,0.170,0.027,None,...,0.514,0.842,0.650,0.009,0.528,5.4,0.006,None,0.046,0.112
7,TCB,1,2019,10.6,1.7,None,None,0.186,0.028,None,...,0.502,0.788,0.680,0.009,0.547,5.1,0.006,None,0.040,-0.001
8,TCB,4,2018,10.7,1.8,None,None,0.215,0.029,None,...,0.498,0.794,0.676,0.009,0.531,5.2,0.008,None,0.047,-0.006
9,TCB,3,2018,11.7,2.1,None,None,0.254,0.032,None,...,0.535,0.862,0.671,0.011,0.488,5.3,0.013,None,0.043,0.215
10,TCB,2,2018,12.8,2.3,None,None,0.243,0.032,None,...,0.555,0.895,0.663,0.011,0.475,5.3,0.010,None,0.261,0.264
11,TCB,1,2018,NaN,NaN,None,None,0.255,0.029,None,...,0.600,0.904,0.713,0.011,0.409,6.3,0.016,None,0.397,0.190
12,TCB,4,2017,NaN,NaN,None,None,0.277,0.026,None,...,0.597,0.941,0.679,0.010,0.392,9.0,0.021,None,0.386,0.128
13,TCB,3,2017,NaN,NaN,None,None,0.251,0.021,None,...,0.588,0.826,0.775,0.011,0.383,11.0,0.022,None,-0.107,0.013
14,TCB,2,2017,NaN,NaN,None,None,0.208,0.018,None,...,0.568,0.766,0.801,0.012,0.416,9.7,0.025,None,0.053,0.032
15,TCB,1,2017,NaN,NaN,None,None,0.201,0.018,None,...,0.592,0.771,0.818,0.011,0.395,10.3,0.024,None,0.052,0.208
16,TCB,4,2016,NaN,NaN,None,None,0.177,0.015,None,...,0.606,0.822,0.787,0.010,0.377,11.0,0.026,None,0.047,0.278
17,TCB,3,2016,NaN,NaN,None,None,0.153,0.013,None,...,0.609,0.829,0.791,0.011,0.366,10.9,0.029,None,0.057,0.444
18,TCB,2,2016,NaN,NaN,None,None,0.122,0.011,None,...,0.601,0.851,0.760,0.011,0.376,11.0,0.033,None,0.046,0.405
19,TCB,1,2016,NaN,NaN,None,None,0.108,0.009,None,...,0.573,0.766,0.809,0.012,0.403,10.7,0.036,None,0.026,0.285
20,TCB,4,2015,NaN,NaN,None,None,0.100,0.009,None,...,0.581,0.785,0.813,0.010,0.380,10.6,0.036,None,0.023,0.390
21,TCB,3,2015,NaN,NaN,None,None,0.090,0.008,None,...,0.536,0.687,0.864,0.012,0.426,9.8,0.039,None,0.026,0.314
22,TCB,2,2015,NaN,NaN,None,None,0.075,0.007,None,...,0.526,0.705,0.824,0.013,0.438,10.0,0.047,None,0.030,0.228
23,TCB,1,2015,NaN,NaN,None,None,0.059,0.005,None,...,0.495,0.699,0.786,0.013,0.463,10.7,0.047,None,0.020,0.235
24,TCB,4,2014,NaN,NaN,None,None,0.075,0.006,None,...,0.457,0.611,0.835,0.011,0.501,10.7,0.033,None,0.012,0.143
25,TCB,3,2014,NaN,NaN,None,None,0.070,0.006,None,...,0.419,0.587,0.803,0.012,0.531,10.5,0.038,None,0.011,0.022
26,TCB,2,2014,NaN,NaN,None,None,0.063,0.005,None,...,0.433,0.593,0.826,0.018,0.513,10.7,0.020,None,0.015,0.060
27,TCB,1,2014,NaN,NaN,None,None,0.055,0.005,None,...,0.438,0.579,0.867,0.020,0.499,10.4,0.019,None,0.038,0.050
28,TCB,4,2013,NaN,NaN,None,None,0.047,0.004,None,...,0.442,0.586,0.869,0.016,0.493,10.4,0.020,None,0.005,0.029
29,TCB,3,2013,NaN,NaN,None,None,-0.047,-0.004,None,...,0.422,0.597,0.817,0.025,0.509,11.0,0.022,None,0.005,0.141

In [18]:
industry_analysis("VNM")

,ticker,marcap,price,numberOfDays,priceToEarning,peg,priceToBook,valueBeforeEbitda,dividend,roe,...,debtOnEquity,debtOnEbitda,income5year,sale5year,income1quarter,sale1quarter,nextIncome,nextSale,rsi,rs
0,VNM,157374,74700,-2,18.3,-1.0,5.2,14.1,0.039,0.271,...,0.2,0.6,-0.037,0.033,-0.187,-0.063,0.060,0.010,37.8,45.0
1,MSN,132264,92900,0,37.1,-0.6,5.1,21.7,0.009,0.121,...,1.9,7.1,0.028,0.152,-0.177,0.057,0.285,0.200,43.4,58.0
2,MCH,52248,72139,-2,9.5,57.5,2.4,8.6,0.000,0.284,...,0.3,1.2,0.207,0.153,0.318,0.139,0.260,0.300,41.9,49.0
3,KDC,15845,61000,-2,44.7,-1.1,2.3,28.1,0.092,0.052,...,0.7,7.0,-0.047,0.123,-0.426,-0.086,-0.202,0.283,47.3,62.0
4,QNS,13512,37824,-3,10.5,3.1,1.8,7.9,0.000,0.177,...,0.3,1.1,0.046,0.016,0.348,-0.153,-0.044,0.140,60.7,56.0
5,MML,11450,35000,0,-78.8,0.7,2.1,-135.7,0.000,-0.027,...,1.0,-43.3,NaN,-0.239,NaN,0.203,-0.719,-0.700,38.4,43.0
6,IDP,10724,181900,0,13.2,-9.0,5.9,10.3,0.008,0.518,...,0.4,0.6,NaN,NaN,-0.139,0.025,0.020,0.120,68.3,84.0
7,SBT,9425,14200,1,12.8,-3.6,1.0,11.2,0.000,0.084,...,1.1,6.4,0.122,0.220,-0.542,0.313,0.128,0.200,47.4,61.0
8,MCM,4168,37970,1,12.1,1.4,1.9,11.6,0.000,0.158,...,0.0,0.1,0.098,0.049,-0.264,-0.054,0.099,0.070,43.9,50.0
9,PAN,3217,15300,-3,8.8,0.4,0.7,5.3,0.000,0.084,...,0.7,3.0,-0.005,0.274,1.362,0.090,0.380,0.450,39.4,27.0
10,VOC,2477,20259,0,-54.1,0.4,1.9,-14.3,0.000,-0.032,...,0.4,-1.9,NaN,-0.181,NaN,0.327,0.116,0.150,35.9,44.0
11,VSF,2450,4900,0,-278.0,2.9,1.1,16.7,0.000,-0.004,...,1.0,7.8,NaN,-0.053,NaN,0.773,-0.939,0.030,77.8,71.0
12,VSN,2023,24700,-1,14.5,-2.0,1.6,10.2,0.000,0.110,...,0.0,1.1,0.012,-0.002,0.289,0.095,-0.034,0.100,51.6,64.0
13,OCH,1380,8000,1,-28.4,0.0,1.4,534.3,0.000,-0.041,...,0.1,53.4,NaN,-0.018,NaN,0.064,6.025,-0.500,43.2,30.0
14,CLX,1083,12329,-3,5.9,0.7,0.7,8.8,0.000,0.122,...,0.0,0.4,0.062,0.089,-0.068,-0.075,0.090,0.300,37.7,26.0
15,LSS,549,7130,-2,13.3,0.6,0.3,3.9,0.000,0.025,...,0.3,2.0,-0.095,-0.005,-0.905,0.299,-0.155,-0.080,53.8,60.0
16,HNF,528,17600,0,4.5,0.0,0.8,5.7,0.000,0.197,...,1.4,2.8,0.191,0.070,-0.555,0.106,-0.473,-0.100,33.9,83.0
17,HSL,160,4810,1,11.5,-2.8,0.4,8.4,0.000,0.043,...,0.0,1.4,-0.086,0.160,0.733,0.037,0.022,0.020,51.1,NaN
18,HKB,36,700,0,-0.6,-1.2,0.2,-2.8,0.000,-0.251,...,0.4,-2.0,NaN,-0.474,NaN,0.170,NaN,NaN,38.7,70.0

In [19]:
stock_ls_analysis("TCB, BID, CEO, GMD")

,ticker,marcap,price,numberOfDays,priceToEarning,peg,priceToBook,dividend,roe,roa,debtOnEquity,income5year,sale5year,income1quarter,sale1quarter,nextIncome,nextSale,rsi,rs
0,GMD,15672,51700,-3,15.7,0.2,2.2,0.0,0.150,0.083,0.3,0.144,-0.003,-0.226,0.075,0.791,0.100,53.7,67.0
1,TCB,93559,26850,1,4.7,0.4,0.8,0.0,0.197,0.032,5.2,0.256,0.200,-0.331,-0.088,0.296,0.228,43.9,45.0
2,BID,224598,43400,-1,12.1,0.2,2.1,0.0,0.199,0.009,19.3,0.218,0.123,-0.207,0.007,0.751,0.067,52.1,68.0
3,CEO,4992,19700,1,18.2,0.1,1.6,0.0,0.089,0.039,0.3,0.094,0.068,5.767,3.483,-0.235,0.300,44.1,44.0

In [22]:
"""report_type: You can choose 1 of 3 reports: BalanceSheet, IncomeStatement, or CashFlow
frequency: Yearly or Quarterly"""
financial_report (symbol='SSI', report_type='BalanceSheet', frequency='Quarterly')

,CHỈ TIÊU,Q3 2020,Q4 2020,Q1 2021,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022
0,TỔNG CỘNG TÀI SẢN,2.693295e+13,3.576953e+13,3.762330e+13,4.190985e+13,4.760360e+13,5.079306e+13,5.008142e+13,4.327169e+13,4.543636e+13,5.222638e+13
1,TÀI SẢN NGẮN HẠN,2.105024e+13,2.904003e+13,3.286192e+13,3.767755e+13,4.131681e+13,4.653960e+13,4.551116e+13,3.884201e+13,4.202427e+13,4.873192e+13
2,Tài sản tài chính ngắn hạn,2.100282e+13,2.888881e+13,3.280760e+13,3.761463e+13,4.123722e+13,4.646427e+13,4.539117e+13,3.869564e+13,4.187383e+13,4.862188e+13
3,Tiền và tương đương tiền,2.123246e+11,3.632519e+11,2.792879e+11,2.433256e+11,2.898345e+11,1.114235e+12,8.049188e+11,2.384802e+11,6.156385e+11,1.417807e+12
4,Tiền,2.123246e+11,2.319712e+11,2.251205e+11,1.942694e+11,2.678036e+11,4.741978e+11,6.067411e+11,1.703772e+11,5.175204e+11,9.072095e+11
...,...,...,...,...,...,...,...,...,...,...,...
155,Vốn ngân sách nhà nước,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
156,Nguồn kinh phí đã hình thành TSCĐ,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
157,LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ (trước 2015),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
158,TỔNG CỘNG NGUỒN VỐN,2.693295e+13,3.576953e+13,3.762330e+13,4.190985e+13,4.760360e+13,5.079306e+13,5.008142e+13,4.327169e+13,4.543636e+13,5.222638e+13
159,LỢI NHUẬN ĐÃ PHÂN PHỐI CHO NHÀ ĐẦU TƯ,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [23]:
financial_flow(symbol="TCB", report_type='incomestatement', report_range='quarterly')

,ticker,revenue,yearRevenueGrowth,quarterRevenueGrowth,costOfGoodSold,grossProfit,operationExpense,operationProfit,yearOperationProfitGrowth,quarterOperationProfitGrowth,...,postTaxProfit,shareHolderIncome,yearShareHolderIncomeGrowth,quarterShareHolderIncomeGrowth,investProfit,serviceProfit,otherProfit,provisionExpense,operationIncome,ebitda
index,,,,,,,,,,,,,,,,,,,,,
2022-Q4,TCB,6819,-0.059,-0.099,None,None,-3990,9427,-0.072,-0.088,...,3572,3544,-0.228,-0.331,-422,2535,495,-691,5437,None
2022-Q3,TCB,7565,0.122,-0.029,None,None,-3014,10338,0.178,-0.062,...,5368,5298,0.221,-0.087,209,2123,441,-609,7324,None
2022-Q2,TCB,7794,0.183,-0.039,None,None,-3286,11024,0.198,0.090,...,5882,5804,0.232,0.054,411,2077,743,-417,7739,None
2022-Q1,TCB,8111,0.325,0.120,None,None,-3108,10112,0.132,-0.005,...,5615,5505,0.252,0.199,-280,1793,488,-218,7004,None
2021-Q4,TCB,7245,0.328,0.074,None,None,-3392,10159,0.309,0.157,...,4684,4592,0.162,0.059,279,2103,532,-627,6767,None
2021-Q3,TCB,6742,0.310,0.023,None,None,-2628,8779,0.171,-0.046,...,4432,4338,0.400,-0.079,384,1497,156,-589,6151,None
2021-Q2,TCB,6588,0.674,0.076,None,None,-2591,9206,0.562,0.031,...,4807,4711,0.672,0.072,717,1457,444,-598,6615,None
2021-Q1,TCB,6124,0.454,0.122,None,None,-2563,8932,0.481,0.151,...,4476,4397,0.790,0.112,812,1325,671,-851,6369,None
2020-Q4,TCB,5456,0.397,0.060,None,None,-2307,7762,0.171,0.035,...,4008,3953,0.305,0.276,546,1069,691,-366,5455,None
2020-Q3,TCB,5148,0.382,0.308,None,None,-2489,7497,0.399,0.272,...,3180,3099,0.213,0.100,378,1145,827,-1034,5008,None
2020-Q2,TCB,3935,0.230,-0.066,None,None,-1839,5895,0.257,-0.022,...,2889,2817,0.169,0.147,298,1254,408,-439,4056,None
2020-Q1,TCB,4212,0.228,0.079,None,None,-2138,6030,0.373,-0.090,...,2506,2456,0.179,-0.189,602,862,354,-772,3893,None
2019-Q4,TCB,3904,0.319,0.048,None,None,-2337,6627,0.311,0.237,...,3119,3029,0.344,0.186,746,1364,613,-312,4290,None
2019-Q3,TCB,3725,0.195,0.165,None,None,-1794,5359,0.156,0.142,...,2583,2554,0.240,0.060,579,635,419,-366,3564,None
2019-Q2,TCB,3199,0.277,-0.068,None,None,-1574,4691,0.173,0.068,...,2433,2409,0.147,0.157,267,756,469,-72,3117,None
2019-Q1,TCB,3430,0.347,0.159,None,None,-1607,4392,-0.058,-0.131,...,2092,2083,0.016,-0.076,158,498,306,-167,2784,None
2018-Q4,TCB,2959,0.198,-0.051,None,None,-2109,5055,-0.132,0.091,...,2265,2254,-0.118,0.094,93,1423,580,-60,2947,None
2018-Q3,TCB,3117,0.516,0.245,None,None,-1315,4635,0.331,0.159,...,2060,2060,0.207,-0.020,126,932,460,-743,3320,None
2018-Q2,TCB,2504,0.127,-0.017,None,None,-1150,3998,0.146,-0.142,...,2101,2101,0.867,0.025,442,688,364,-220,2848,None
2018-Q1,TCB,2547,0.166,0.031,None,None,-1267,4660,0.268,-0.200,...,2049,2049,0.934,-0.198,1392,492,229,-824,3393,None
2017-Q4,TCB,2469,0.290,0.201,None,None,-1553,5823,0.860,0.672,...,2555,2555,1.826,0.498,459,2247,647,-1073,4269,None
2017-Q3,TCB,2055,0.021,-0.075,None,None,-1218,3482,0.238,-0.002,...,1706,1706,0.669,0.517,479,644,303,-157,2263,None
2017-Q2,TCB,2222,0.011,0.017,None,None,-972,3490,0.230,-0.051,...,1125,1125,0.420,0.062,236,500,531,-1109,2518,None
2017-Q1,TCB,2184,0.080,0.141,None,None,-1080,3675,0.162,0.174,...,1059,1059,1.227,0.172,712,546,233,-1270,2595,None
2016-Q4,TCB,1915,-0.071,-0.049,None,None,-1282,3131,0.261,0.113,...,904,904,1.406,-0.116,239,400,578,-716,1849,None
2016-Q3,TCB,2012,0.290,-0.084,None,None,-1094,2813,0.340,-0.008,...,1022,1022,1.530,0.291,218,499,83,-442,1719,None
2016-Q2,TCB,2198,0.275,0.087,None,None,-927,2837,0.322,-0.103,...,792,792,0.614,0.665,173,304,161,-905,1910,None
2016-Q1,TCB,2022,0.086,-0.019,None,None,-982,3163,0.204,0.274,...,476,476,0.517,0.266,217,558,366,-1599,2181,None
2015-Q4,TCB,2062,0.296,0.321,None,None,-1161,2484,0.278,0.183,...,376,376,1.089,-0.070,-177,351,248,-837,1323,None
2015-Q3,TCB,1560,-0.027,-0.095,None,None,-905,2100,0.011,-0.021,...,404,404,1.496,-0.176,-59,337,262,-675,1195,None
2015-Q2,TCB,1724,0.343,-0.074,None,None,-799,2146,0.389,-0.184,...,491,491,1.284,0.565,-14,232,202,-723,1347,None
2015-Q1,TCB,1862,0.439,0.170,None,None,-832,2628,0.704,0.352,...,314,314,-0.403,0.743,220,219,327,-1388,1796,None
2014-Q4,TCB,1591,0.437,-0.008,None,None,-1099,1943,0.430,-0.064,...,180,180,0.869,0.111,-22,232,142,-590,844,None
2014-Q3,TCB,1604,0.575,0.249,None,None,-766,2077,0.619,0.344,...,162,162,2.027,-0.247,140,240,92,-1096,1311,None
2014-Q2,TCB,1284,0.395,-0.008,None,None,-776,1545,0.120,0.002,...,215,215,1.266,-0.591,-7,215,53,-493,769,None
2014-Q1,TCB,1294,0.003,0.169,None,None,-790,1542,-0.052,0.134,...,525,525,0.322,4.457,92,435,-279,-79,752,None
2013-Q4,TCB,1107,0.164,0.087,None,None,-800,1359,0.156,0.059,...,96,96,NaN,0.799,-2,218,36,-431,560,None
2013-Q3,TCB,1018,-0.280,0.106,None,None,-873,1283,-0.065,-0.070,...,53,53,-0.911,-0.436,-8,151,121,-313,410,None
2013-Q2,TCB,921,-0.357,-0.286,None,None,-771,1379,0.024,-0.152,...,95,95,-0.843,-0.761,89,244,125,-353,608,None
2013-Q1,TCB,1290,-0.021,0.356,None,None,-912,1627,-0.121,0.384,...,397,397,-0.613,NaN,82,122,132,-317,714,None
2012-Q4,TCB,951,NaN,-0.327,None,None,-1263,1175,NaN,-0.144,...,-1216,-1216,NaN,NaN,-81,39,266,-1128,-88,None
2012-Q3,TCB,1414,NaN,-0.013,None,None,-615,1373,NaN,0.019,...,603,603,NaN,0.002,-201,151,9,-155,758,None
2012-Q2,TCB,1432,NaN,0.086,None,None,-574,1347,NaN,-0.272,...,602,602,NaN,-0.414,-119,228,-194,-170,773,None
2012-Q1,TCB,1318,NaN,NaN,None,None,-826,1851,NaN,NaN,...,1028,1028,NaN,NaN,120,147,266,3,1025,None
2010-Q2,TCB,814,NaN,NaN,None,None,-446,972,NaN,NaN,...,384,384,NaN,NaN,26,104,28,-142,526,None

In [24]:
financial_flow(symbol="TCB", report_type='balancesheet', report_range='quarterly')

,ticker,shortAsset,cash,shortInvest,shortReceivable,inventory,longAsset,fixedAsset,asset,debt,...,oweCentralBank,valuablePaper,payableInterest,receivableInterest,deposit,otherDebt,fund,unDistributedIncome,minorShareHolderProfit,payable
index,,,,,,,,,,,,,,,,,,,,,
2022-Q4,TCB,None,4216,None,None,None,None,8411,699033,585608,...,8,34007,6144,8029,358404,34007,11609,64483,1129,585608
2022-Q3,TCB,None,3026,None,None,None,None,7282,671354,561454,...,6,42858,4750,8681,318919,42858,9151,64059,1032,561454
2022-Q2,TCB,None,3204,None,None,None,None,7220,623739,519263,...,2,37122,3375,8072,321634,37122,9152,58761,963,519263
2022-Q1,TCB,None,3277,None,None,None,None,7265,615270,516684,...,223,32731,3369,7253,328914,32731,9156,52958,884,516684
2021-Q4,TCB,None,3579,None,None,None,None,7224,568811,475756,...,1,33680,3098,5808,314753,33680,9156,47469,845,475756
2021-Q3,TCB,None,3303,None,None,None,None,7106,541635,453251,...,15,34003,3074,6224,316376,34003,6784,45261,753,453251
2021-Q2,TCB,None,3554,None,None,None,None,6739,504304,420403,...,0,27678,2643,5736,289335,27678,6790,40924,659,420403
2021-Q1,TCB,None,4273,None,None,None,None,4726,462823,383730,...,2,26035,2897,5664,287446,26035,6790,36213,563,383730
2020-Q4,TCB,None,3664,None,None,None,None,4613,439603,364988,...,0,27900,3252,5185,277459,27900,6790,31816,484,364988
2020-Q3,TCB,None,4205,None,None,None,None,4273,401462,330853,...,0,22785,3736,5988,252572,22785,5172,29503,457,330853
2020-Q2,TCB,None,4106,None,None,None,None,4126,395861,328432,...,0,23404,3928,5598,249857,23404,5173,26404,376,328432
2020-Q1,TCB,None,4151,None,None,None,None,3493,391808,327217,...,1004,17472,3613,6614,235099,17472,5173,23587,340,327217
2019-Q4,TCB,None,4821,None,None,None,None,3208,383699,321627,...,0,17461,3479,5554,231297,17461,5173,21130,292,321627
2019-Q3,TCB,None,5409,None,None,None,None,3504,367538,308598,...,2000,14489,3542,5112,218655,14489,3858,19439,201,308598
2019-Q2,TCB,None,5034,None,None,None,None,3439,360662,304296,...,3063,12642,3797,4649,220263,12642,3866,16885,173,304296
2019-Q1,TCB,None,4785,None,None,None,None,3104,326112,272237,...,2699,12866,3498,4739,207978,12866,3868,14486,79,272237
2018-Q4,TCB,None,2606,None,None,None,None,1719,321049,269267,...,6025,13178,3425,5738,201471,13178,3868,12403,69,269267
2018-Q3,TCB,None,4042,None,None,None,None,1586,311796,262315,...,2000,17240,3563,6036,193583,17240,2651,11388,0,262315
2018-Q2,TCB,None,3590,None,None,None,None,1489,300405,252975,...,2000,18904,3079,4672,186283,18904,6148,15156,0,252975
2018-Q1,TCB,None,3671,None,None,None,None,1483,273153,235537,...,2000,20074,2861,4400,181391,20074,6148,13055,0,235537
2017-Q4,TCB,None,2344,None,None,None,None,1511,269392,242462,...,1000,17640,2764,3877,170971,17640,6157,10997,0,242462
2017-Q3,TCB,None,3137,None,None,None,None,1461,233502,214069,...,2000,11495,2938,5728,166323,11495,5219,9380,0,214069
2017-Q2,TCB,None,2873,None,None,None,None,1473,232342,210591,...,1000,10320,2888,5231,172103,10320,5219,7673,0,210591
2017-Q1,TCB,None,3179,None,None,None,None,1529,232522,211870,...,432,10397,2426,4440,178623,10397,5219,6548,0,211870
2016-Q4,TCB,None,2957,None,None,None,None,1583,235363,215731,...,1448,10415,2195,3989,173449,10415,5223,5531,0,215731
2016-Q3,TCB,None,2930,None,None,None,None,1513,222770,204027,...,0,9842,2353,4758,163515,9842,4745,5125,0,204027
2016-Q2,TCB,None,2840,None,None,None,None,1562,212676,194941,...,0,8048,2488,4365,150033,8048,4745,4102,0,194941
2016-Q1,TCB,None,2750,None,None,None,None,880,199003,182047,...,0,8103,2283,3362,148817,8103,4745,3310,0,182047
2015-Q4,TCB,None,2754,None,None,None,None,882,192009,175481,...,0,8134,2087,3047,142240,8134,4753,2897,0,175481
2015-Q3,TCB,None,2758,None,None,None,None,931,175217,159056,...,0,6395,1982,3874,136631,6395,4549,2740,0,159056
2015-Q2,TCB,None,2559,None,None,None,None,975,172744,156989,...,0,6477,1901,3590,129016,6477,4550,2337,0,156989
2015-Q1,TCB,None,2495,None,None,None,None,1011,179100,163806,...,203,6442,1829,3278,126886,6442,4550,1858,0,163806
2014-Q4,TCB,None,2724,None,None,None,None,1037,175915,160916,...,0,6254,1908,3341,131438,6254,4552,1570,0,160916
2014-Q3,TCB,None,2277,None,None,None,None,996,170768,155946,...,0,5571,1665,4692,121733,5571,4371,1572,0,155946
2014-Q2,TCB,None,2469,None,None,None,None,1022,171081,156420,...,0,4619,2265,5430,124743,4619,0,1410,0,156420
2014-Q1,TCB,None,2123,None,None,None,None,981,164135,149686,...,0,4659,2309,5508,124014,4659,4372,1194,0,149686
2013-Q4,TCB,None,2291,None,None,None,None,1033,158897,144977,...,0,5643,1861,5257,119978,5643,4370,672,0,144977
2013-Q3,TCB,None,2421,None,None,None,None,1069,165879,152031,...,0,4536,1734,5637,117236,4536,4279,718,0,152031
2013-Q2,TCB,None,2999,None,None,None,None,1033,171394,157611,...,0,6670,2151,6986,111591,6670,4279,627,0,157611
2013-Q1,TCB,None,3669,None,None,None,None,1125,175863,162188,...,0,7646,1901,5874,114096,7646,3476,1355,0,162188
2012-Q4,TCB,None,4529,None,None,None,None,1146,179733,166443,...,0,10451,1783,5074,111462,10451,3475,966,0,166443
2012-Q3,TCB,None,6523,None,None,None,None,1257,178267,163863,...,0,18987,2278,5643,99560,18987,3332,2291,0,163863
2012-Q2,TCB,None,5853,None,None,None,None,1240,179792,165883,...,2900,20819,2426,5198,96739,20819,3339,1892,0,165883

In [25]:
financial_flow(symbol="TCB", report_type='cashflow', report_range='quarterly')

        ticker  investCost  fromInvest  fromFinancial  fromSale  freeCashFlow
index
2022-Q4    TCB        -720        -679           -700     19130             0
2022-Q3    TCB        -212        -205             63     15950             0
2022-Q2    TCB         -65         -62              0     -4020             0
2022-Q1    TCB        -113        -111            -73     24408             0
2021-Q4    TCB        -280        -276              0     -9328             0
2021-Q3    TCB        -180        -179             60     17974             0
2021-Q2    TCB        -337        -282              0     11205             0
2021-Q1    TCB        -143        -143              0     -6954             0
2020-Q4    TCB        -268        -263           -137      -479             0
2020-Q3    TCB        -157        -157              0    -12204             0
2020-Q2    TCB         -61         -56            -37     -1274             0
2020-Q1    TCB        -195        -194              0      3884             0
2019-Q4    TCB         -84         -79          -2165      1959             0
2019-Q3    TCB         -54         -45          -1000       797             0
2019-Q2    TCB        -110        -109             12      3717             0
2019-Q1    TCB         -10          11             58      6253             0
2018-Q4    TCB        -215        -215             58     -5302             0
2018-Q3    TCB        -128        -128          -1508     -5810             0
2018-Q2    TCB         -28         -34           6518     19534             0
2018-Q1    TCB         -15         884           8632     -8163             0
2017-Q4    TCB        -110        -105           4800      1506             0
2017-Q3    TCB         -51         -51          -4043      2862             0
2017-Q2    TCB          -6          -5             16     -1675             0
2017-Q1    TCB          -9         917             -8      4385             0
2016-Q4    TCB        -136        -134              0      1381             0
2016-Q3    TCB         -14         -14              0      -977             0
2016-Q1    TCB         -56         -57              0     -6851             0
2015-Q4    TCB         -46          23              0     -5688             0
2015-Q3    TCB         -20          37              0       455             0
2015-Q2    TCB         -25         -18              0      6506             0
2015-Q1    TCB         -33         -33              0     -8160             0
2014-Q4    TCB        -122        -631              0     -5217             0
2014-Q3    TCB         -33         -29              0      5048             0
2014-Q2    TCB         -28         -19              0      2291             0
2014-Q1    TCB          -5         -11              0      -350             0
2013-Q4    TCB        -198        -201              0     -8213             0
2013-Q3    TCB         -66         -93              0      2271             0
2013-Q2    TCB         -25         -16              0      2008             0
2013-Q1    TCB         -35         -29              0     -1153             0
2012-Q3    TCB         -66       -1391              0     -2139             0

In [26]:
dividend_history("VNM")

   exerciseDate  cashYear  cashDividendPercentage issueMethod
0      22/12/22      2022                   0.140        cash
1      06/07/22      2021                   0.095        cash
2      06/07/22      2022                   0.150        cash
3      10/01/22      2021                   0.140        cash
4      07/09/21      2021                   0.150        cash
5      07/06/21      2020                   0.110        cash
6      05/01/21      2020                   0.100        cash
7      29/09/20      2020                   0.200        cash
8      29/06/20      2019                   0.150        cash
9      26/12/19      2019                   0.100        cash
10     16/09/19      2019                   0.200        cash
11     05/06/19      2018                   0.150        cash
12     27/12/18      2018                   0.100        cash
13     05/09/18      2018                   0.200        cash
14     05/06/18      2017                   0.150        cash
15     28/12/17      2017                   0.150        cash
16     14/08/17      2017                   0.200        cash
17     04/05/17      2016                   0.200        cash
18     19/08/16      2016                   0.400        cash
19     03/06/16      2015                   0.200        cash

In [27]:
general_rating("VNM")

,stockRating,valuation,financialHealth,businessModel,businessOperation,rsRating,taScore,ticker,highestPrice,lowestPrice,priceChange3m,priceChange1y,beta,alpha
0,3.7,1.4,4.8,3.0,2.8,2.1,1.5,VNM,83504.0,61242.1,-0.012,-0.03,0.55,0.0012

In [28]:
biz_model_rating("VNM")

,ticker,businessModel,businessEfficiency,assetQuality,cashFlowQuality,bom,businessAdministration,productService,businessAdvantage,companyPosition,industry,operationRisk
0,VNM,3.0,3,3,3,3,3,3,3,3,3,3

In [29]:
biz_operation_rating("VNM")

,industryEn,loanGrowth,depositGrowth,netInterestIncomeGrowth,netInterestMargin,costToIncome,netIncomeTOI,ticker,businessOperation,avgROE,avgROA,last5yearsNetProfitGrowth,last5yearsRevenueGrowth,last5yearsOperatingProfitGrowth,last5yearsEBITDAGrowth,last5yearsFCFFGrowth,lastYearGrossProfitMargin,lastYearOperatingProfitMargin,lastYearNetProfitMargin,TOIGrowth
0,Food Products,None,None,None,None,None,None,VNM,2.8,5,5,1,2,1,1,2,4,3,3,None

In [30]:
financial_health_rating("VNM")

,industryEn,loanDeposit,badLoanGrossLoan,badLoanAsset,provisionBadLoan,ticker,financialHealth,netDebtEquity,currentRatio,quickRatio,interestCoverage,netDebtEBITDA
0,Food Products,None,None,None,None,VNM,4.8,4,5,5,5,5

In [31]:
valuation_rating("VNM")

      industryEn ticker  valuation  pe  pb  ps  evebitda  dividendRate
0  Food Products    VNM        1.4   1   1   1         1             4

In [32]:
industry_financial_health("VNM")

,industryEn,loanDeposit,badLoanGrossLoan,badLoanAsset,provisionBadLoan,ticker,financialHealth,netDebtEquity,currentRatio,quickRatio,interestCoverage,netDebtEBITDA
0,None,None,None,None,None,VNM,3.4,4,4,3,3,3

In [33]:
market_top_mover('ForeignTrading')

,foreignBuyVolume,foreignBuyValue,foreignSellVolume,foreignSellValue,organCode,ticker,sectorName,value,volume,price,...,o,h,l,priceChange,percentPriceChange,rank,totalRank,performance,financial,technical
0,5473200.0,1.123793e+11,793500.0,1.627565e+10,HPG,HPG,Thép và sản phẩm thép,3.552184e+11,17300348.0,20600.0,...,20300.0,20900.0,20250.0,400.0,0.019802,1,47,"{'organCode': 'HPG', 'percentPriceChange1Day':...","{'organCode': 'HPG', 'rtd7': 16510.9055471241,...","{'organCode': 'HPG', 'sma20Past4': 20707.5, 's..."
1,1557000.0,2.137920e+10,183000.0,2.506635e+09,VND,VND,Môi giới chứng khoán,1.368849e+11,9969716.0,13900.0,...,13700.0,13900.0,13500.0,450.0,0.033457,1,43,"{'organCode': 'VND', 'percentPriceChange1Day':...","{'organCode': 'VND', 'rtd7': 11918.553698522, ...","{'organCode': 'VND', 'sma20Past4': 15232.5, 's..."
2,1025300.0,1.518793e+10,43200.0,6.345550e+08,HSG,HSG,Thép và sản phẩm thép,2.319195e+11,15718618.0,14850.0,...,14400.0,15100.0,14350.0,450.0,0.031250,2,47,"{'organCode': 'HSG', 'percentPriceChange1Day':...","{'organCode': 'HSG', 'rtd7': 16979.0577316899,...","{'organCode': 'HSG', 'sma20Past4': 13992.5, 's..."
3,1154100.0,2.556494e+10,172800.0,3.808335e+09,KBC,KBC,Bất động sản,5.378728e+10,2429216.0,22450.0,...,22200.0,22500.0,21850.0,550.0,0.025114,24,131,"{'organCode': 'KBC', 'percentPriceChange1Day':...","{'organCode': 'KBC', 'rtd7': 20955.5926843609,...","{'organCode': 'KBC', 'sma20Past4': 24945.0, 's..."
4,1149700.0,2.068252e+10,556200.0,1.000219e+10,HDB,HDB,Ngân hàng,2.672156e+10,1487494.0,17650.0,...,18000.0,18200.0,17650.0,-400.0,-0.022161,11,27,"{'organCode': 'HDB', 'percentPriceChange1Day':...","{'organCode': 'HDB', 'rtd7': 14691.7286608859,...","{'organCode': 'HDB', 'sma20Past4': 17535.0, 's..."
5,726000.0,8.595245e+09,139900.0,1.652665e+09,PVPOWER,POW,Sản xuất & Phân phối Điện,4.208591e+10,3556092.0,11850.0,...,11800.0,11950.0,11750.0,150.0,0.012821,5,48,"{'organCode': 'PVPOWER', 'percentPriceChange1D...","{'organCode': 'PVPOWER', 'rtd7': 12982.7693031...","{'organCode': 'PVPOWER', 'sma20Past4': 12022.5..."
6,774000.0,1.453958e+10,210700.0,3.940400e+09,SSI,SSI,Môi giới chứng khoán,1.158409e+11,6182287.0,18900.0,...,18750.0,18900.0,18500.0,400.0,0.021622,3,43,"{'organCode': 'SSI', 'percentPriceChange1Day':...","{'organCode': 'SSI', 'rtd7': 14938.1925557089,...","{'organCode': 'SSI', 'sma20Past4': 19880.0, 's..."
7,694500.0,1.435140e+10,295500.0,6.095315e+09,PVD,PVD,Thiết bị và Dịch vụ Dầu khí,6.278425e+10,3033950.0,20600.0,...,20850.0,21000.0,20500.0,0.0,0.000000,2,9,"{'organCode': 'PVD', 'percentPriceChange1Day':...","{'organCode': 'PVD', 'rtd7': 24922.5689401644,...","{'organCode': 'PVD', 'sma20Past4': 19802.5, 's..."
8,335400.0,4.460440e+09,39000.0,5.170450e+08,DIG,DIG,Bất động sản,6.341305e+10,4776396.0,13250.0,...,13250.0,13500.0,13100.0,0.0,0.000000,26,131,"{'organCode': 'DIG', 'percentPriceChange1Day':...","{'organCode': 'DIG', 'rtd7': 12363.9470648678,...","{'organCode': 'DIG', 'sma20Past4': 15715.0, 's..."
9,277500.0,2.134506e+09,20800.0,1.617980e+08,HAG,HAG,Nuôi trồng nông & hải sản,5.636779e+10,7328807.0,7650.0,...,7720.0,7790.0,7600.0,-30.0,-0.003906,11,112,"{'organCode': 'HAG', 'percentPriceChange1Day':...","{'organCode': 'HAG', 'rtd7': 5430.6656650715, ...","{'organCode': 'HAG', 'sma20Past4': 9116.0, 'sm..."
10,282100.0,3.406215e+09,37400.0,4.561000e+08,HAMADECO,HHV,Xây dựng,4.246454e+10,3522431.0,12050.0,...,12000.0,12250.0,11850.0,300.0,0.025532,6,354,"{'organCode': 'HAMADECO', 'percentPriceChange1...","{'organCode': 'HAMADECO', 'rtd7': 23355.570904...","{'organCode': 'HAMADECO', 'sma20Past4': 11977...."
11,226800.0,3.163155e+09,0.0,0.000000e+00,LVB,LPB,Ngân hàng,6.703446e+10,4855719.0,13700.0,...,14000.0,14000.0,13600.0,-150.0,-0.010830,13,27,"{'organCode': 'LVB', 'percentPriceChange1Day':...","{'organCode': 'LVB', 'rtd7': 13911.9075281756,...","{'organCode': 'LVB', 'sma20Past4': 14337.5, 's..."
12,423000.0,1.121296e+10,208600.0,5.536575e+09,KDH,KDH,Bất động sản,2.924631e+10,1101878.0,26600.0,...,26550.0,26900.0,26200.0,600.0,0.023077,16,131,"{'organCode': 'KDH', 'percentPriceChange1Day':...","{'organCode': 'KDH', 'rtd7': 16121.9167021603,...","{'organCode': 'KDH', 'sma20Past4': 27300.0, 's..."
13,204200.0,3.189600e+09,0.0,0.000000e+00,BSRC,BSR,Sản xuất và Khai thác dầu khí,7.762262e+10,4989600.0,15600.0,...,15700.0,16000.0,15300.0,-200.0,-0.015000,1,3,"{'organCode': 'BSRC', 'percentPriceChange1Day'...","{'organCode': 'BSRC', 'rtd7': 16442.5082919343...","{'organCode': 'BSRC', 'sma20Past4': 15525.2, '..."
14,202000.0,3.976210e+09,1000.0,1.960000e+07,CEO,CEO,Bất động sản,8.292070e+10,4226000.0,19700.0,...,19500.0,20000.0,19300.0,300.0,0.015464,12,131,"{'organCode': 'CEO', 'percentPriceChange1Day':...","{'organCode': 'CEO', 'rtd7': 12686.8033111022,...","{'organCode': 'CEO', 'sma20Past4': 21465.0, 's..."
15,196500.0,5.021120e+09,0.0,0.000000e+00,BMI,BMI,Bảo hiểm phi nhân thọ,7.371406e+09,288271.0,25900.0,...,25350.0,25900.0,25000.0,550.0,0.021696,1,12,"{'organCode': 'BMI', 'percentPriceChange1Day':...","{'organCode': 'BMI', 'rtd7': 22092.3618381963,...","{'organCode': 'BMI', 'sma20Past4': 24395.0, 's..."
16,200300.0,2.454075e+09,7200.0,8.830000e+07,MSB,MSB,Ngân hàng,8.911963e+09,728116.0,12250.0,...,12200.0,12300.0,12200.0,50.0,0.004098,14,27,"{'organCode': 'MSB', 'percentPriceChange1Day':...","{'organCode': 'MSB', 'rtd7': 13326.999, 'rtd11...","{'organCode': 'MSB', 'sma20Past4': 13042.5, 's..."
17,293200.0,2.467252e+09,100600.0,8.410680e+08,ASM,ASM,Nuôi trồng nông & hải sản,1.561120e+10,1866834.0,8500.0,...,8400.0,8500.0,8280.0,210.0,0.025332,7,112,"{'organCode': 'ASM', 'percentPriceChange1Day':...","{'organCode': 'ASM', 'rtd7': 14896.3615288184,...","{'organCode': 'ASM', 'sma20Past4': 8982.5, 'sm..."
18,196600.0,3.192580e+09,14800.0,2.404600e+08,TNG,TNG,Hàng May mặc,2.204189e+10,1361200.0,16200.0,...,16700.0,16900.0,16000.0,200.0,0.012500,2,61,"{'organCode': 'TNG', 'percentPriceChange1Day':...","{'organCode': 'TNG', 'rtd7': 17029.2962375111,...","{'organCode': 'TNG', 'sma20Past4': 14924.551, ..."
19,183600.0,2.041595e+09,2400.0,2.676000e+07,IJC,IJC,Bất động sản,1.095413e+10,987791.0,11150.0,...,10900.0,11250.0,10800.0,350.0,0.032407,55,131,"{'organCode': 'IJC', 'percentPriceChange1Day':...","{'organCode': 'IJC', 'rtd7': 15172.5745363399,...","{'organCode': 'IJC', 'sma20Past4': 11816.5475,..."
20,1048900.0,1.854711e+10,881100.0,1.557940e+10,E1VFVN30,E1VFVN30,Quỹ đầu tư,5.417462e+09,306353.0,17650.0,...,18200.0,18200.0,17590.0,-140.0,-0.007870,3,14,"{'organCode': 'E1VFVN30', 'percentPriceChange1...","{'organCode': 'E1VFVN30', 'rtd7': None, 'rtd11...","{'organCode': 'E1VFVN30', 'sma20Past4': 18528...."
21,222800.0,8.745160e+09,57200.0,2.244765e+09,DGW,DGW,Phân phối hàng chuyên dụng,1.680597e+10,428373.0,39200.0,...,39400.0,39600.0,38700.0,200.0,0.005128,2,30,"{'organCode': 'DGW', 'percentPriceChange1Day':...","{'organCode': 'DGW', 'rtd7': 14570.3922155445,...","{'organCode': 'DGW', 'sma20Past4': 40835.0, 's..."
22,242800.0,3.061395e+09,79100.0,1.001505e+09,GELEX,GEX,Thiết bị điện,1.148293e+11,9091614.0,12500.0,...,12800.0,12900.0,12400.0,-300.0,-0.023438,1,27,"{'organCode': 'GELEX', 'percentPriceChange1Day...","{'organCode': 'GELEX', 'rtd7': 14194.023463034...","{'organCode': 'GELEX', 'sma20Past4': 13737.5, ..."
23,192200.0,7.375420e+09,30000.0,1.151590e+09,IDICO,IDC,Bất động sản,7.785939e+10,2025100.0,38600.0,...,37700.0,39000.0,37700.0,1000.0,0.026596,1,131,"{'organCode': 'IDICO', 'percentPriceChange1Day...","{'organCode': 'IDICO', 'rtd7': 16142.391291217...","{'organCode': 'IDICO', 'sma20Past4': 38040.0, ..."
24,159800.0,3.960570e+09,0.0,0.000000e+00,PCC1,PC1,Xây dựng,3.305215e+10,1340980.0,24400.0,...,24950.0,25000.0,24350.0,-100.0,-0.004082,1,354,"{'organCode': 'PCC1', 'percentPriceChange1Day'...","{'organCode': 'PCC1', 'rtd7': 18891.7733992651...","{'organCode': 'PCC1', 'sma20Past4': 24522.5, '..."
25,145900.0,5.936660e+08,18100.0,7.345700e+07,HNG,HNG,Nuôi trồng nông & hải sản,5.996011e+09,1472447.0,4080.0,...,4100.0,4100.0,4030.0,70.0,0.017456,25,112,"{'organCode': 'HNG', 'percentPriceChange1Day':...","{'organCode': 'HNG', 'rtd7': 2746.6613537991, ...","{'organCode': 'HNG', 'sma20Past4': 4424.5, 'sm..."
26,309500.0,2.865663e+10,183000.0,1.689500e+10,MSN,MSN,Thực phẩm,3.635182e+10,392969.0,92900.0,...,92900.0,93400.0,91600.0,0.0,0.000000,18,112,"{'organCode': 'MSN', 'percentPriceChange1Day':...","{'organCode': 'MSN', 'rtd7': 18369.1653838409,...","{'organCode': 'MSN', 'sma20Past4': 97245.0, 's..."
27,168900.0,4.290300e+09,46000.0,1.168340e+09,VCSC,VCI,Môi giới chứng khoán,6.192375e+10,2434179.0,25350.0,...,25300.0,25950.0,25100.0,350.0,0.014000,2,43,"{'organCode': 'VCSC', 'percentPriceChange1Day'...","{'organCode': 'VCSC', 'rtd7': 14914.9704895432...","{'organCode': 'VCSC', 'sma20Past4': 27865.0, '..."
28,151400.0,5.305070e+09,57200.0,1.997620e+09,HAH,HAH,"Kho bãi, hậu cần và bảo dưỡng",2.196143e+10,628338.0,34800.0,...,35000.0,35500.0,34550.0,450.0,0.013100,1,113,"{'organCode': 'HAH', 'percentPriceChange1Day':...","{'organCode': 'HAH', 'rtd7': 33463.4815677783,...","{'organCode': 'HAH', 'sma20Past4': 35952.5, 's..."
29,100100.0,1.707930e+09,6200.0,1.065000e+08,OCB,OCB,Ngân hàng,6.756396e+09,396916.0,17350.0,...,16800.0,17350.0,16700.0,500.0,0.029674,17,27,"{'organCode': 'OCB', 'percentPriceChange1Day':...","{'organCode': 'OCB', 'rtd7': 18448.4882418702,...","{'organCode': 'OCB', 'sma20Past4': 18172.5, 's..."

In [34]:
fr_trade_heatmap ('All', 'FrBuyVol')

,organCode,name,value,percentPriceChange,referencePrice,matchPrice,ceilingPrice,floorPrice,industry_name,rate
0,PVD,PVD,694500.0,0.000000,20600.0,20600.0,22000.0,19200.0,Dầu khí,-0.001759
1,BSRC,BSR,204200.0,-0.015000,15800.0,15600.0,18100.0,13500.0,Dầu khí,-0.001759
2,PVS,PVS,129400.0,0.004115,24300.0,24400.0,26700.0,21900.0,Dầu khí,-0.001759
3,PETRO,PLX,63300.0,0.002639,37900.0,38000.0,40550.0,35250.0,Dầu khí,-0.001759
0,HPG,HPG,5473200.0,0.019802,20200.0,20600.0,21600.0,18800.0,Nguyên vật liệu,0.012986
...,...,...,...,...,...,...,...,...,...,...
9,LVB,LPB,226800.0,-0.010830,13850.0,13700.0,14800.0,12900.0,Ngân hàng,-0.007736
10,None,Khác,479400.0,0.005208,0.0,0.0,0.0,0.0,Ngân hàng,-0.007736
0,FPT,FPT,166177.0,0.001239,80700.0,80800.0,86300.0,75100.0,Công nghệ Thông tin,0.001090
1,CMG,CMG,3000.0,0.000000,41900.0,41900.0,44800.0,39000.0,Công nghệ Thông tin,0.001090
2,VTC,VTC,100.0,0.031746,12600.0,13000.0,13800.0,11400.0,Công nghệ Thông tin,0.001090

In [35]:
get_latest_indices()

,indexId,comGroupCode,indexValue,tradingDate,indexChange,percentIndexChange,referenceIndex,openIndex,closeIndex,highestIndex,...,foreignSellVolumeTotal,foreignTotalRoom,foreignCurrentRoom,totalStockUnderFloor,totalStockOverCeiling,matchVolume,matchValue,ceiling,floor,marketStatus
0,0,VNINDEX,1038.64,2023-02-14T00:00:00,-5.06,-0.004800,1043.70,1045.14,1038.64,1046.64,...,34329177.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
1,0,VN30,1034.93,2023-02-14T00:00:00,-5.47,-0.005300,1040.40,1040.85,1034.93,1042.96,...,22560277.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
2,0,HNXIndex,204.86,2023-02-14T00:00:00,0.37,0.001796,204.49,204.49,204.86,205.43,...,250705.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
3,0,HNX30,347.28,2023-02-14T00:00:00,2.61,0.007587,344.67,344.79,347.28,349.71,...,198205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
4,0,UpcomIndex,77.94,2023-02-14T00:00:00,0.74,0.009632,77.20,77.21,77.94,78.36,...,80300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
5,0,VNXALL,1575.74,2023-02-14T00:00:00,-1.35,-0.000900,1577.09,1577.22,1575.74,1584.38,...,31667882.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
6,0,VN100,978.90,2023-02-14T00:00:00,-2.07,-0.002100,980.97,982.92,978.90,985.41,...,30093077.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
7,0,VNALL,983.94,2023-02-14T00:00:00,-1.30,-0.001300,985.24,987.35,983.94,989.78,...,31848577.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
8,0,VNCOND,1440.98,2023-02-14T00:00:00,-3.19,-0.002200,1444.17,1449.22,1440.98,1450.62,...,3334600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
9,0,VNCONS,737.05,2023-02-14T00:00:00,-2.81,-0.003800,739.86,741.34,737.05,743.11,...,1549000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
10,0,VNDIAMOND,1571.68,2023-02-14T00:00:00,-1.98,-0.001300,1573.66,1579.02,1571.68,1582.73,...,11446877.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
11,0,VNENE,525.89,2023-02-14T00:00:00,5.03,0.009700,520.86,525.27,525.89,526.52,...,504400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
12,0,VNFIN,1144.27,2023-02-14T00:00:00,-0.45,-0.000400,1144.72,1148.64,1144.27,1154.92,...,14140200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
13,0,VNFINLEAD,1476.61,2023-02-14T00:00:00,-0.24,-0.000200,1476.85,1481.45,1476.61,1491.52,...,13526200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
14,0,VNFINSELECT,1531.39,2023-02-14T00:00:00,-0.64,-0.000400,1532.03,1537.21,1531.39,1545.51,...,14140200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
15,0,VNHEAL,1587.20,2023-02-14T00:00:00,-4.93,-0.003100,1592.13,1584.37,1587.20,1591.20,...,2000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
16,0,VNIND,581.03,2023-02-14T00:00:00,-0.14,-0.000200,581.17,584.55,581.03,585.88,...,1052600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
17,0,VNIT,2531.86,2023-02-14T00:00:00,3.39,0.001300,2528.47,2529.53,2531.86,2535.71,...,231277.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
18,0,VNMAT,1477.72,2023-02-14T00:00:00,24.46,0.016800,1453.26,1458.29,1477.72,1491.34,...,1846800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
19,0,VNMID,1276.36,2023-02-14T00:00:00,7.06,0.005600,1269.30,1276.69,1276.36,1284.85,...,7532800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
20,0,VNREAL,872.73,2023-02-14T00:00:00,-13.53,-0.015300,886.26,881.70,872.73,883.95,...,8974400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
21,0,VNSI,1586.18,2023-02-14T00:00:00,-12.91,-0.008100,1599.09,1597.97,1586.18,1601.51,...,5663577.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
22,0,VNSML,1084.28,2023-02-14T00:00:00,9.10,0.008500,1075.18,1079.49,1084.28,1086.54,...,1755500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
23,0,VNUTI,871.84,2023-02-14T00:00:00,4.13,0.004800,867.71,871.63,871.84,878.11,...,207200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None
24,0,VNX50,1660.95,2023-02-14T00:00:00,-4.44,-0.002700,1665.39,1665.45,1660.95,1671.67,...,25197477.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None

In [36]:
get_index_series(index_code='VNINDEX', time_range='OneYear')

,comGroupCode,indexValue,tradingDate,indexChange,percentIndexChange,referenceIndex,openIndex,closeIndex,highestIndex,lowestIndex,matchVolume,matchValue,totalMatchVolume,totalMatchValue
0,VNINDEX,1492.75,2022-02-15T00:00:00,20.79,0.014124,1471.96,1471.96,1492.75,1495.56,1470.06,538527000.0,1.743939e+13,538527000.0,1.743939e+13
1,VNINDEX,1492.10,2022-02-16T00:00:00,-0.65,-0.000400,1492.75,1499.07,1492.10,1499.50,1486.68,594459500.0,1.770122e+13,594459500.0,1.770122e+13
2,VNINDEX,1507.99,2022-02-17T00:00:00,15.89,0.010649,1492.10,1492.10,1507.99,1507.99,1492.10,687250992.0,2.141057e+13,687250992.0,2.141057e+13
3,VNINDEX,1504.84,2022-02-18T00:00:00,-3.15,-0.002100,1507.99,1494.30,1504.84,1507.29,1492.38,645883900.0,2.107072e+13,645883900.0,2.107072e+13
4,VNINDEX,1510.84,2022-02-21T00:00:00,6.00,0.004000,1504.84,1504.96,1510.84,1516.63,1500.97,708058800.0,2.197164e+13,708058800.0,2.197164e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,VNINDEX,1064.03,2023-02-09T00:00:00,-8.19,-0.007600,1072.22,1070.07,1064.03,1075.20,1064.03,363991072.0,6.767541e+12,363991072.0,6.767541e+12
248,VNINDEX,1055.30,2023-02-10T00:00:00,-8.73,-0.008200,1064.03,1066.16,1055.30,1066.28,1054.08,385841692.0,6.665340e+12,385841692.0,6.665340e+12
249,VNINDEX,1043.70,2023-02-13T00:00:00,-11.60,-0.011000,1055.30,1050.99,1043.70,1054.05,1031.70,578047487.0,8.912452e+12,578047487.0,8.912452e+12
250,VNINDEX,1042.63,2023-02-14T09:27:51,-1.07,-0.001000,1043.70,1045.14,1042.63,1046.64,1040.94,65100.0,1.066000e+09,34624300.0,5.004520e+11
251,VNINDEX,1038.64,2023-02-14T15:02:00,-5.06,-0.004800,1043.70,1045.14,1038.64,1046.64,1032.76,290522000.0,4.983477e+12,325146300.0,5.483929e+12